# modules/admin_panel.py
import streamlit as st
import sqlite3
import os
import pandas as pd
from datetime import datetime, timedelta

# --- DATABASE CONNECTION ---
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DB_PATH = os.path.join(BASE_DIR, "database", "ai_portal.db")

def get_connection():
    return sqlite3.connect(DB_PATH, check_same_thread=False)

# --- ANALYTICS DATA FETCHING ---
def fetch_system_metrics():
    """Fetches high-level metrics for the dashboard."""
    conn = get_connection()
    cursor = conn.cursor()
    
    metrics = {}
    cursor.execute("SELECT COUNT(id) FROM users")
    metrics['total_users'] = cursor.fetchone()[0] or 0
    
    cursor.execute("SELECT COUNT(id) FROM universal_docs")
    metrics['total_ocr_docs'] = cursor.fetchone()[0] or 0
    
    cursor.execute("SELECT COUNT(id) FROM chat_history WHERE app_type = 'LightRAG' AND role = 'user'")
    metrics['total_rag_queries'] = cursor.fetchone()[0] or 0
    
    cursor.execute("SELECT AVG(confidence_score) FROM universal_docs")
    avg_conf = cursor.fetchone()[0]
    metrics['avg_confidence'] = round(avg_conf, 1) if avg_conf else 0.0

    conn.close()
    return metrics

def fetch_recent_audit_log(limit=50):
    conn = get_connection()
    query = """
        SELECT u.username, d.filename, d.doc_category, d.confidence_score, d.extraction_date 
        FROM universal_docs d
        JOIN users u ON d.user_id = u.id
        ORDER BY d.extraction_date DESC
        LIMIT ?
    """
    df = pd.read_sql_query(query, conn, params=(limit,))
    conn.close()
    return df

def fetch_user_table():
    conn = get_connection()
    query = "SELECT id, username, created_at FROM users ORDER BY created_at DESC"
    df = pd.read_sql_query(query, conn)
    conn.close()
    return df

# --- API COST SAVINGS ENGINE (LOCAL OVERRIDE) ---
def calculate_estimated_savings(metrics):
    """
    Calculates estimated INR saved by running Gemma 4 locally instead of using Cloud APIs.
    OCR: ~₹0.99 per page (Cloud Multimodal API baseline)
    RAG: ~₹0.05 per query.
    """
    ocr_savings = metrics['total_ocr_docs'] * 2 * 0.99 
    rag_savings = metrics['total_rag_queries'] * 0.05
    total_savings = ocr_savings + rag_savings
    
    return {
        "ocr_saved_inr": round(ocr_savings, 2),
        "rag_saved_inr": round(rag_savings, 2),
        "total_saved_inr": round(total_savings, 2)
    }

def generate_mock_timeseries_data(total_docs):
    dates = [(datetime.today() - timedelta(days=i)).strftime("%Y-%m-%d") for i in range(6, -1, -1)]
    if total_docs == 0:
        counts = [0] * 7
    else:
        import random
        counts = [random.randint(0, max(1, total_docs // 3)) for _ in range(6)]
        counts.append(abs(total_docs - sum(counts)))
    return pd.DataFrame({"Date": dates, "Documents Processed": counts}).set_index("Date")

# --- MAIN UI RENDERER ---
def render_admin_panel():
    st.header("🛡️ Local Infrastructure Console")
    st.markdown("Global overview of local system usage, compute savings, and offline activity.")
    
    if st.session_state.username != "admin":
        st.warning("⚠️ **Admin Privileges Required.**")
        st.info("You are currently viewing the admin dashboard in 'Demo Mode'.")
    
    with st.spinner("Compiling Local Telemetry..."):
        metrics = fetch_system_metrics()
        savings = calculate_estimated_savings(metrics)
        audit_df = fetch_recent_audit_log()
        users_df = fetch_user_table()
        chart_data = generate_mock_timeseries_data(metrics['total_ocr_docs'])

    st.divider()

    st.subheader("📊 Global System Metrics")
    m1, m2, m3, m4 = st.columns(4)
    with m1:
        st.metric(label="👥 Total Registered Users", value=metrics['total_users'], delta="Active")
    with m2:
        st.metric(label="📑 Total OCR Extractions", value=metrics['total_ocr_docs'])
    with m3:
        st.metric(label="🧠 Total RAG Queries", value=metrics['total_rag_queries'])
    with m4:
        st.metric(label="🎯 Avg OCR Confidence", value=f"{metrics['avg_confidence']}%")

    st.divider()

    col_chart, col_finance = st.columns([2, 1])
    with col_chart:
        st.subheader("📈 7-Day Processing Volume")
        st.bar_chart(chart_data, color="#3b82f6", width='stretch')
        
    with col_finance:
        st.subheader("💰 Cloud Computing Savings (INR)")
        st.info("Value generated by hosting 100% locally.")
        
        st.markdown(f"""
        * **Vision Extraction Savings:** ₹{savings['ocr_saved_inr']}
        * **RAG Retrieval Savings:** ₹{savings['rag_saved_inr']}
        """)
        
        st.metric(label="Total Corporate Savings", value=f"₹ {savings['total_saved_inr']}", delta="Retained in-house")

    st.divider()

    tab1, tab2 = st.tabs(["📋 Global Audit Log", "👥 User Management"])
    with tab1:
        st.markdown("#### Real-time Offline Processing Log")
        if audit_df.empty:
            st.write("No documents processed yet.")
        else:
            st.dataframe(audit_df, width='stretch', hide_index=True)
            
    with tab2:
        st.markdown("#### Registered Platform Users")
        if users_df.empty:
            st.write("No users found.")
        else:
            st.dataframe(users_df, width='stretch', hide_index=True)