services:
  - type: web
    name: ocr-v2-1
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8501"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
